name: Dev deploy
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Create env file
        run: |
          touch .env
          echo DEPLOY_ENV=development >> .env
          cat .env
      - name: Build
        run: |
          env CXXFLAGS="-std=c++17" npm ci --legacy-peer-deps --omit=dev
          npm run test:unit
          npm run build-and-test:e2e:ci
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy
        uses: jonelantha/gatsby-s3-action@v3
        with:
          dest-s3-bucket: ${{ secrets.AWS_S3_DEV_BUCKET }}
          cloudfront-id-to-invalidate: ${{ secrets.AWS_CLOUDFRONT_DEV_ID }}
